#ifndef GL_CONFIG_H_HEADER_GUARD
#define GL_CONFIG_H_HEADER_GUARD

#define GL_MAX_DIRECTIONAL_LIGHT_COUNT 4
#define GL_MAX_PROXIMAL_POINT_LIGHT_COUNT 16
#define GL_MAX_PROXIMAL_SPOT_LIGHT_COUNT 16

#endif // GL_CONFIG_H_HEADER_GUARD